<?php

namespace ContainerBHFEXzh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J4kCUgWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J4kCUgW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J4kCUgW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'player' => ['privates', '.errored..service_locator.J4kCUgW.App\\Entity\\Player', NULL, 'Cannot autowire service ".service_locator.J4kCUgW": it needs an instance of "App\\Entity\\Player" but this type has been excluded in "config/services.yaml".'],
            'teamRepository' => ['privates', 'App\\Repository\\TeamRepository', 'getTeamRepositoryService', true],
            'transferService' => ['privates', 'App\\Service\\TransferService', 'getTransferServiceService', true],
        ], [
            'entityManager' => '?',
            'player' => 'App\\Entity\\Player',
            'teamRepository' => 'App\\Repository\\TeamRepository',
            'transferService' => 'App\\Service\\TransferService',
        ]);
    }
}
