<?php

namespace ContainerBHFEXzh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransferPlayerTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TransferPlayerType' shared autowired service.
     *
     * @return \App\Form\TransferPlayerType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TransferPlayerType.php';

        return $container->privates['App\\Form\\TransferPlayerType'] = new \App\Form\TransferPlayerType();
    }
}
