<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Player extends \App\Entity\Player implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'marketPrice' => [parent::class, 'marketPrice', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'onMarket' => [parent::class, 'onMarket', null],
        "\0".parent::class."\0".'surname' => [parent::class, 'surname', null],
        "\0".parent::class."\0".'team' => [parent::class, 'team', null],
        'id' => [parent::class, 'id', null],
        'marketPrice' => [parent::class, 'marketPrice', null],
        'name' => [parent::class, 'name', null],
        'onMarket' => [parent::class, 'onMarket', null],
        'surname' => [parent::class, 'surname', null],
        'team' => [parent::class, 'team', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
