<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXQKR4km\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXQKR4km/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXQKR4km.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXQKR4km\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXQKR4km\App_KernelDevDebugContainer([
    'container.build_hash' => 'XQKR4km',
    'container.build_id' => '7978eb54',
    'container.build_time' => 1703858779,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXQKR4km');
